### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by eloekset** [OfficeDev/office-ui-fabric-js#101]
Do you have a NuGet package for TypeScript - either definition files or a jquery.fabric.ts file?

**Comment by ericthompson** [comment]
[Fabric JS is currently available on NuGet](http://www.nuget.org/packages/OfficeUIFabricJS/).

For the definition files, [we've added a card to the Fabric JS Trello board](https://trello.com/c/S7rgV8Ip/28-typescript-definitions-for-components) to track it. You can vote for it there so we can help gauge interest. Thanks!
