### ISSUE TITLE
CommandBar: ContextualMenu dropdowns don't work unless overflow button present

### ISSUE THREAD

**Issue by wcarson** [OfficeDev/office-ui-fabric-js#113]
I'm trying to get a CommandBar working as the main navigation for a web app (NavBar variant). The problem I'm seeing is that for commands with a ContextualMenu to work, there has to be an overflow command present in the CommandBar even if it's not needed or used. Is this intended behavior or am I missing something. 

In the code sample below (full html -> [commandbar.txt](https://github.com/OfficeDev/office-ui-fabric-js/files/472623/commandbar.txt)), if the `ms-CommandBar-overflowButton` div is present everything works. If it's not there the context menu no longer works. It's also worth noting that all of the elements of the overflow command have to be present (buttons, icons, items, links) for this to work.

```
<div class="ms-CommandBar">
  <div class="ms-CommandBar-mainArea">     
    <div class="ms-CommandButton ms-CommandButton--pivot">
      <button class="ms-CommandButton-button">
         <span class="ms-CommandButton-label">Dropdown</span>
         <span class="ms-CommandButton-dropdownIcon"><i class="ms-Icon ms-Icon--ChevronDown"></i></span>
      </button>
      <ul class="ms-ContextualMenu">
        <li class="ms-ContextualMenu-item ">
          <a class="ms-ContextualMenu-link">Option 1</a>
        </li>
        <li class="ms-ContextualMenu-item ">
          <a class="ms-ContextualMenu-link">Option 1</a>
        </li>
      </ul>
    </div>

    <!-- If this element is present, dropdown above works. If not present dropdown stops working -->
    <div class="ms-CommandButton ms-CommandBar-overflowButton">
      <button class="ms-CommandButton-button"  >
        <span class="ms-CommandButton-icon "><i class="ms-Icon ms-Icon--More"></i></span>
        <span class="ms-CommandButton-label"></span>
      </button>
      <ul class="ms-ContextualMenu">
        <li class="ms-ContextualMenu-item">
          <a class="ms-ContextualMenu-link"></a>
          <i class="ms-Icon ms-Icon--Folder"></i>
        </li>
      </ul>
    </div>
    
  </div>
</div>
```

**Comment by ericthompson** [comment]
Good question, @wcarson - it is the intended behavior for the ellipsis to be there. That's the standard Office 365 overflow behavior for commanding/navigation surfaces.

It won't show up, though, if you have a small number of nav/command items - it will only show if necessary.
