### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by Abrissirba** [OfficeDev/office-ui-fabric-js#121]
I just recently noticed the react path you have taken and have been trying to grasp what the future will be for the javascript version. Will this repo still get some atention? I checked the Trello board you are referring to and there is a lot of requests but nothing in the "In development" or "Done" columns. Would love a clarification in the documentation about what the future of this repo will be like.

**Comment by ericthompson** [comment]
Right now, we've moved our focus to the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) components as that's what the product teams across Office and SharePoint are currently using and building out. We'll continue to monitor this repo and watch for PRs, Issues, and requests, but our contributions will be fairly limited while momentum continues with the [Core](https://github.com/OfficeDev/office-ui-fabric-core) and React projects.

That said, by all means contribute and [vote up what you'd like to see](https://trello.com/b/wq7oIK87/office-ui-fabric-js-requests) as this helps us understand the community's greatest needs.
