### ISSUE TITLE
Callout documentation is outdated

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/office-ui-fabric-js#123]
It looks like the html snippet provided in the Callout documentation not longer works. A new class set is needed the `ms-ContextualHost` classes

**Comment by ericthompson** [comment]
@bpatra - we're assuming this is in a version you're trying to run (not our localhost site)?

You shouldn't have to create a ContextualHost. Could you try it in a JSFiddle?

**Comment by bpatra** [comment]
Hi, I used plunker. I could not use JSFiddle I do not have CDN for fabric 4.0 and fabric-js 1.1.0
http://plnkr.co/edit/WUd3JTXqnULKOFf9aesC

**Comment by mikewheaton** [comment]
You'll also need to add the JavaScript to your page to make the Callout work.

Here is the code snippet from [the Callout documentation](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Callout.md):

```
 <script type="text/javascript">
  var CalloutExamples = document.querySelectorAll(".ms-CalloutExample");
  for(var i = 0; i < CalloutExamples.length; i++) {
    var Example = CalloutExamples[i];
    var ExampleButtonElement = Example.querySelector(".ms-CalloutExample-button .ms-Button");
    var CalloutElement = Example.querySelector(".ms-Callout");
    new fabric['Callout'](
          CalloutElement, 
          ExampleButtonElement,
          "right"
    );
  }
</script>
```

See a [working fork of your Plunk here](http://plnkr.co/edit/wB9BLyuI2LPmcoIbVc0r?p=preview).

**Comment by bpatra** [comment]
Thank you, I was not using the component correctly
