### ISSUE TITLE
README.md css CDN references not available

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/office-ui-fabric-js#125]
the CDN references `https://appsforoffice.microsoft.com/fabric/3.0.0/fabric.min.cs` `https://appsforoffice.microsoft.com/fabric/1.0.0/fabric.components.min.css` lead to 404 error

**Comment by mikewheaton** [comment]
We'll investigate why Fabric 1.0.0 is not available on the CDN. However, you probably don't want to use such an old version.

Are you trying to use the new Fabric Core and Fabric JS projects? The latest release on the CDN of Fabric Core is 4.0.0 (https://appsforoffice.microsoft.com/fabric/fabric-core/4.0.0/fabric.css). It looks like Fabric JS 1.0.0 has not yet made it to the CDN. For that project, you will have to host your own copy which you can find in the downloads section of the [release page](https://github.com/OfficeDev/office-ui-fabric-js/releases/tag/v1.1.0).

**Comment by bpatra** [comment]
Yes I am using the core 4.0 and the new fabric js 1.1.0.
This issue has been created as a reminder for updating the README.md.

**Comment by ericthompson** [comment]
@bpatra - we've done some digging and found answers!

If you're trying to reference Fabric 1.0.0 - the very first release of Fabric - the correct reference is actually:
`https://appsforoffice.microsoft.com/fabric/1.0/fabric.components.min.css`

I believe you're trying to reference the new, Fabric JS component's 1.0.0 release which is:
`https://appsforoffice.microsoft.com/fabric/fabric-js/1.0.0/fabric.components.min.css`

The reference you'd want for Fabric Core is actually 4.0.0 (as @mikewheaton mentioned) which can be found at:
`https://appsforoffice.microsoft.com/fabric/fabric-core/4.0.0/fabric.min.css`

PR #135 should correct these documentation issues - we apologize for the inconvenience here!
