### ISSUE TITLE
Blocked2 Icon missing from CDN

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#13]
_From @mikewheaton on July 23, 2016 17:27_

The `Blocked2` icon, which is used in the MessageBar component, is not included in the icon font on our CDN. This causes a bug where no icon is shown in that MessageBar variant:

![image](https://cloud.githubusercontent.com/assets/1382445/17079281/f7ee1dae-50bf-11e6-83aa-200d1647d771.png)

_Copied from original issue: OfficeDev/office-ui-fabric-core#738_

**Comment by ericthompson** [comment]
Fixed as of v1.1.0. Closing for now.
