### ISSUE TITLE
Documentation missing (md or localhost site) for variants of components

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/office-ui-fabric-js#133]
Right now, the [md files](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/COMPONENTSLIST.md) and the [localhost site](https://github.com/OfficeDev/office-ui-fabric-js#clone-build-and-view-the-docs) don't actually display the code for the non-standard/basic/default variants of the components.

**Comment by leddie24** [comment]
Will be fixed in new site
