### ISSUE TITLE
Numbering and code snippets are garbled in component md documentation files

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/office-ui-fabric-js#134]
It looks like the component md documentation files are using the `<pre> <code>` syntax for some portions of the code snippets which throws off the numbering and makes for inconsistent code appearance:
![image](https://cloud.githubusercontent.com/assets/1420854/18873085/ba6f2626-848b-11e6-9a45-8b69aeb7fb93.png)

It looks like the ``` syntax may fit better here, or use a different (non-standard) md syntax for the numbering (like 1.), 2.), etc.).

**Comment by leddie24** [comment]
This will be fixed in the updated JS website
