### ISSUE TITLE
Version differences and documentation not clear

### ISSUE THREAD

**Issue by sjclemmy** [OfficeDev/office-ui-fabric-js#138]
I've just gone through re-adding the bower dependencies in a project I am working on to match how you have re-organised the repositories. Specifically because I wanted to use the 'Layer' component as the documentation implies this exists in the -js variant. However now I've done this, I see that office-ui-fabric points to the 2.6.1 of office-ui-fabric-js. So there is no 'Layer' component in the -js variant, it only exists in the react version (I'm assuming) and the update I've done is not an update to the components, only to the core styles.

The implication of this is that if I install core, js and the ngOfficeUIFabric variant (as I have), the ngOfficeUIFabric will not work correctly as the old styles have been removed.

I just wanted to point out that the documentation is convoluted and unclear. I imagine that you were probably under pressure to release for the ignite conference, but the lack of clarity has meant I have had to unpick what you've done.

**Comment by ericthompson** [comment]
Thanks for the feedback, @sjclemmy. Our new site and the multiple sub-projects means that we're still settling into the new structure of the project and its associated documentation, so we appreciate you sharing your experience.

Are you referring to [this layer component](http://dev.office.com/fabric#/components/layer)? You're correct that this component only exists in the [Fabric React project](https://github.com/OfficeDev/office-ui-fabric-react). Components that are available in Fabric JS are specified by an aside at the top of the component page that says "Also available in" (e.g. the [breadcrumb's page](http://dev.office.com/fabric#/components/breadcrumb)) and by the [components overview page](http://dev.office.com/fabric#/components).

office-ui-fabric (in contrast to office-ui-fabric-core or office-ui-fabric-js) on bower does, in fact, point to our last stable version of Fabric that included components - 2.6.1. This is also the same dependency for the ngOfficeUIFabric project as their site and project displays. If you'd like to use ngOfficeUIFabric, v2.6.1 of Office UI Fabric appears to be the right way to go.

We'll get some work on the backlog to update the [ngOfficeUIFabric page on our site](http://dev.office.com/fabric#/angular-js) to more clearly document the nature of that dependency and also look into ways to help navigate folks to the right location for the version/sub-project they're looking for. We're also currently looking at improvements to the documentation around Fabric JS and hope to have something up soon.

Again, thanks for the feedback!
