### ISSUE TITLE
People picker selected list does not show circular image with small resolution device

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/office-ui-fabric-js#139]
Hello, 
I noticed the following glitch when using peoplepicker in small resolution mode.
![facepile-peoplepicker](https://cloud.githubusercontent.com/assets/2801702/18919077/282a83e2-859d-11e6-9eca-79e869ee9b2f.jpg)

**Comment by ericthompson** [comment]
Thanks for catching this, @bpatra - tracking it now on our side.
