### ISSUE TITLE
Missing command button in Fabric JS

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-ui-fabric-js#141]
The [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react) contains CSS definition for a button component with the **command** modifier: `.ms-Button--command` This kind of button is not defined in **office-ui-fabric-js**.
### Expected behavior

Using the `fabric.css` and `fabric.components.css` I should be able to define command button with an icon:

``` html
<p>Command button</p>
<button class="ms-Button ms-Button--command">
  <span class="ms-Button-icon"><i class="ms-Icon ms-Icon--Add"></i></span>
  <span class="ms-Button-label">Create account</span>
</button>
```

![screenshot_100416_085332_am](https://cloud.githubusercontent.com/assets/287778/19064832/21356634-8a10-11e6-9b8a-dcbda4602767.jpg)
### Actual behavior

Fabric JS button component is rendered as a normal `.ms-Button` only.

**Comment by ericthompson** [comment]
Hi @jozefizso - although *slightly* different, would [this CommandButton](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/CommandButton.md) suit your needs?

**Comment by ericthompson** [comment]
Closing for now - feel free to reopen if this isn't the droid you're looking for 😏
