### ISSUE TITLE
Add JS to the CDN

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-js#143]
All the CDNs I'm seeing are for the css files but not the JS file. 

I'm using this currently: https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.5/fabric.min.js

but it doesn't seem to have the ProgressIndicator function.

**Comment by mikewheaton** [comment]
The file you found on CDNJS is for a [different project named Fabric](https://github.com/kangax/fabric.js).

The JS for this project should be on our CDN, but I'm having trouble finding the URL for it. I'll dig around some more and see where it is.

**Comment by simkessy** [comment]
Yea you're right. I guess Office Fabric isn't on CDNj. It'd be nice if it was because I can't find it in the docs.

**Comment by magnusjansson** [comment]
I'm missing the js file in the CDN too. Please upload it

**Comment by mikewheaton** [comment]
Quick update here: We have a pull request into our CDN open now and these files should be available within a few days.

**Comment by Reezaali** [comment]
@mikewheaton, can you merge the README change you made where you added all the updated CDN links to all the files please? Thanks!

**Comment by mikewheaton** [comment]
@Reezaali: That [pull request](https://github.com/OfficeDev/office-ui-fabric-js/pull/207) just needs one more approver and then we can get it merged in. I'll poke some people. 😄

**Comment by ericthompson** [comment]
@mikewheaton - this is now in, correct?

**Comment by mikewheaton** [comment]
Yes, it's been merged. I'll close this now.

**Comment by ericthompson** [comment]
Cool - thanks, @mikewheaton!
