### ISSUE TITLE
Panel dismiss error

### ISSUE THREAD

**Issue by paylord** [OfficeDev/office-ui-fabric-js#147]
When closing a panel by clicking on the overlay all is fine.

When closing a panel clicking on the close button then it works the first time but subsequent times it throws a console error.  The panel does close correctly and it is not obvious if the console is not open.

The error is when the panelHost dismiss function tries to removeChild saying it is not found.  It actually seems to loop through this multiple times (number of times panel is opened -1) so I did wonder if it was related to the eventListeners stacking?

**Comment by ericthompson** [comment]
Thanks for identifying this, @paylord. We'll take a look.

**Comment by leddie24** [comment]
Fixed in #154.

**Comment by paylord** [comment]
Thanks :)
