### ISSUE TITLE
Dropdown TypeError: item is undefined onItemSelection()

### ISSUE THREAD

**Issue by seriewe** [OfficeDev/office-ui-fabric-js#148]
In FireFox 49.0.1 the Dropdown Selection does not work because of the nonstandard alias evt.srcElement.

Error: TypeError: item is undefined

Please change to Event.target inside  Dropdown.prototype._onItemSelection method.

Best Regards

**Comment by ericthompson** [comment]
Thanks for identifying the bug, @seriewe - would you mind submitting a pull request with your fix?

**Comment by seriewe** [comment]
Hi Eric,
I cloned the repo create a branch and fixed the issue, but I'm not able to publish my branch and create a pull request, did I missed something? I'm also not able to create a fork on the repo.

**Comment by ericthompson** [comment]
Thanks, @seriewe - I'm testing it out now 👍
