### ISSUE TITLE
Feature Request: Button Group

### ISSUE THREAD

**Issue by vinny75** [OfficeDev/office-ui-fabric-js#149]
Button Groups similar to BootStrap's button group, http://v4-alpha.getbootstrap.com/components/button-group/, for normal buttons and command buttons for use in command bar (use case would be day-week-month view in a calendar app)

**Comment by ericthompson** [comment]
Thanks for the request and explanation of your scenario, @vinny75.

I've gone ahead and created a card on the [Trello board for Fabric JS](https://trello.com/c/N1JFXVOD/31-button-group-component) so we can track the request.
