### ISSUE TITLE
DatePicker: How do you set the format and localization?

### ISSUE THREAD

**Issue by Tran-Kien** [OfficeDev/office-ui-fabric-js#150]
How is the format and the locale set on the DatePicker?
I'm using the following example: 
https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/DatePicker.md

Thanks

**Comment by ericthompson** [comment]
Hi @Tran-Kien - we use pickadate.js to power the Fabric JS Date Picker and it has a [publicly posted API](http://amsul.ca/pickadate.js/api/) that you can reference. It includes info on [formats supported by the plugin](http://amsul.ca/pickadate.js/date/#formats) and how it can support [translations/other languages](http://amsul.ca/pickadate.js/date/#translations).

Let me know if you have further questions!
