### ISSUE TITLE
Icons pages broken in localhost docs

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/office-ui-fabric-js#156]
When you build the localhost docs, the 2 icons pages are formatted a bit wonky and don't display the icons:
![image](https://cloud.githubusercontent.com/assets/1420854/19280025/d2472dda-8f98-11e6-82d4-ddfb4c9f95cf.png)
![image](https://cloud.githubusercontent.com/assets/1420854/19280035/de593780-8f98-11e6-8b37-248e4ab350e4.png)

**Comment by leddie24** [comment]
Hey @ericthompson, we actually removed the Icons/MDL2 Icons pages out of the JS repo samples section.   Anything not related to JS components are strictly inside of core now.  If you delete dist and rebuild, it shouldn't be there.

**Comment by ericthompson** [comment]
That works - thanks!
