### ISSUE TITLE
Unable to turn off checkbox column on DetailsList

### ISSUE THREAD

**Issue by vivmaha** [OfficeDev/office-ui-fabric-js#157]
I would like to use the DetailsList, but I do not want the checkbox column (especially for my single item selection).

Can this column be optional?

**Comment by Jahnp** [comment]
Hi @vivmaha, thanks for reporting this issue! However, the DetailsList is a component in the [Fabric-React](https://github.com/OfficeDev/office-ui-fabric-react/) project, not Fabric-JS--would you mind opening your issue there? Thanks! We'll go ahead and close this in the meantime.

**Comment by vivmaha** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/issues/406

Thanks.
