### ISSUE TITLE
Path to Libraries incorrect in samples HTML

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#16]
_From @dmitriyyepishin on July 15, 2016 20:15_

Sample HTML files in documentation\Components\ has incorrect have incorrect path to Fabric JS and CSS files. The path is missing one "..". For example

`<script type="text/javascript" src="../../js/fabric.js"></script> `

should be

`<script type="text/javascript" src="../../../js/fabric.js"></script>`

_Copied from original issue: OfficeDev/office-ui-fabric-core#727_

**Comment by leddie24** [comment]
This should be resolved.  Taken care of in #80 .
