### ISSUE TITLE
DetailsList

### ISSUE THREAD

**Issue by paylord** [OfficeDev/office-ui-fabric-js#165]
There is a DetailsList demo on the web site but this only seems to be available in React.
http://dev.office.com/fabric#/components/detailslist

It looks like this was partially added at some point but not completed?

Are there plans to add DetailsList to this library?  Or am I just looking in the wrong place?

Thanks

Dave

**Comment by ericthompson** [comment]
Hi @paylord - unfortunately, the DetailsList isn't available in Fabric JS. This component includes a ton of extra functionality and JavaScript that makes it better suited for the [Fabric React project](https://github.com/OfficeDev/office-ui-fabric-react).

[This component has been added to our Trello requests board](https://trello.com/c/6uEsdZFG/6-details-list-similar-to-file-list-in-onedrive) - feel free to vote it up if you'd like to see it in the JS library.
