### ISSUE TITLE
Contextual Menu Crash

### ISSUE THREAD

**Issue by echoworxdev** [OfficeDev/office-ui-fabric-js#176]
Hi there,
I am using OfficeUIFabric Core 5.0.0 with with OfficeUIFabricJS 1.1.0 for building an Office365 add-in.
The application crashes on the "click event" (the second time) in the IE 11 browser with the following message:
![cd258d6a-a2b7-11e6-9198-632ffd90a38f](https://cloud.githubusercontent.com/assets/23174758/20024558/c977d096-a2bd-11e6-98fe-9c1ff8bfa0e5.png)

To my understanding it  crashes on the following line:
  this._container.parentNode.removeChild(this._container); 
 (fabric.js, Line 2089:   Function: ContextualHost.prototype.disposeModal())

**Comment by mikewheaton** [comment]
We just released [Fabric JS 1.2.0](https://github.com/OfficeDev/office-ui-fabric-js/releases/tag/1.2.0) earlier today and it sounds like this could be related to a bug that was fixed there. Could you give it a try?

**Comment by Jahnp** [comment]
Yeah, this sounds like the problem #167 should have solved.

**Comment by echoworxdev** [comment]
That solves the issue. Thanks

**Comment by Jahnp** [comment]
Awesome, thanks for the quick follow-up @echoworxdev!
