### ISSUE TITLE
Missing vendor prefixes for transform css instruction

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/office-ui-fabric-js#177]
I stumbled on the following error with Safari ~~9~~ (edit Safari 8).
The .ms-Dialog uses `transform` css but the `ms-Dialog` do not use all necessary vendor prefixes.
According to [shouldiprefix.com transforms](http://shouldiprefix.com/#transforms) we should use -ms and -webkit prefixes as well. 

I can fix that with a PR but I would like to introduce a common mixin to handle this. There is no "Common" sass mixin file (in office-ui-fabric-js at least).

**Comment by mikewheaton** [comment]
We configure Autoprefixer on [line 216 of Documentation.js](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/gulp/Documentation.js#L216) to support the last 2 versions of most browsers, and IE 9+.

The latest major version of Safari is 10, so I would have expected it to include any prefixes that are needed for 9. But after taking a closer look at [Can I use](http://caniuse.com/#feat=transforms2d), it seems they consider Safari 9.1 to be a major version. This could be why Autoprefixer is not adding the `webkit-` prefix.

Given how easy it is to support older browsers and the very limited impact on file size, should we consider setting Autoprefixer to target the last 3 versions?

**Comment by Jahnp** [comment]
+1 to just adding deeper support via autoprefixer if that actually does the job.

**Comment by mikewheaton** [comment]
I've confirmed that changing it to `last 3 versions` adds the `webkit-` prefix. Pull request coming soon.
