### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by carlosvdh** [OfficeDev/office-ui-fabric-js#183]
I am not able to find doc on how to use the datepicker to set a date 
```

var picker = new fabric['DatePicker'](datepickerelements[i]);
picker.set('select', [2015, 3, 20]);

```
This throws an exception. How can I get to the Picker object to be able to use the pickadate API?

**Comment by leddie24** [comment]
Hey @carlosvdh , this should be resolved now.  You can use the pickadateAPI like so now:


```
datepicker = new fabric['DatePicker']('.ms-Datepicker');
// Change selected date
datepicker.picker.set('select', [2012, 0, 1]);

// Change highlighted date
datepicker.picker.set('highlight', [2015, 3, 20])
```

**Comment by carlosvdh** [comment]
Thenks @leddie24 !! Works now. (
