### ISSUE TITLE
Issue: Multiple Dropdowns stay opened simultaneously

### ISSUE THREAD

**Issue by echoworxdev** [OfficeDev/office-ui-fabric-js#184]
Hi there,
I am using OfficeUIFabric Core 5.0.0 with with OfficeUIFabricJS 1.2.0 for building an Office365 add-in.

As you might have figured from the Title of the issue;
if you click open a drop down, and click on second drop down right after, the second one will open up up while the first stays open too.

Kindly look into it.
Thank you

**Comment by ericthompson** [comment]
Thanks for reporting - we'll take a look. Any ideas what might be causing it?

**Comment by echoworxdev** [comment]
Hi Eric,
I didn't get a chance to debug into fabric.js, but my guess would be that we are not removing properly, some attribute/ class (most likely 'is-open' class) from all other Dropdowns when one dropdown is clicked at.
Again, just a guess.
Attaching some screenshots to better reflect the issue.
Thanks

Initial Screen:
![image](https://cloud.githubusercontent.com/assets/23174758/20276117/f563976e-aa68-11e6-8a4b-9cbb1da9f660.png)

First Dropdown open 
![image](https://cloud.githubusercontent.com/assets/23174758/20276130/0653189c-aa69-11e6-9f03-5143f4f581b4.png)


Second Dropdown Open:
![image](https://cloud.githubusercontent.com/assets/23174758/20276143/12c6869a-aa69-11e6-9801-497571831f93.png)


Both Dropdowns open overlap:
![image](https://cloud.githubusercontent.com/assets/23174758/20276154/1fb35c7a-aa69-11e6-9849-2dd9f292d761.png)

**Comment by echoworxdev** [comment]
Hi there,
I saw the commit you made to the src.
Now, am I supposed to wait for the next OfficeUIFabric JS to get the changes?
I am using OfiiceUIFabric JS as a Nuget package in Visual Studio.

**Comment by mikewheaton** [comment]
@echoworxdev: Yes, you'll have to wait for [Fabric JS 1.3.0](https://github.com/OfficeDev/office-ui-fabric-js/milestone/3?closed=1) to be released and published to NuGet. We don't have a definite timeline (we're working on establishing a more predictable release cadence) but it should be out in the next week or so.

**Comment by echoworxdev** [comment]
Thanks for the quick response.
Looking forward to next release.
