### ISSUE TITLE
Clarify checkbox documentation

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#185]
https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/CheckBox.md 

Please add a clarifying note that says something like:
"To toggle between the checked / unchecked states, change the value of the aria-checked attribute to true or false."

Thanks!

**Comment by ericthompson** [comment]
Thanks for this clarification - we'll take a look as we reassess our documentation for this project.

**Comment by Reezaali** [comment]
An alternative may be to provide documentation / code samples describing the use of the check, unCheck, and toggle functions. Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali.  Here's an example of using the component methods with CheckBox below.  The updated site (once it's live) should cover components in more detail.

```
var CheckBoxElements = document.querySelectorAll(".ms-CheckBox");
var CheckBoxComponents = [];
for(var i = 0; i < CheckBoxElements.length; i++) {
     CheckBoxComponents[i] = new fabric['CheckBox'](CheckBoxElements[i]);
}
CheckBoxComponents[0].toggle(); // Toggles first checkbox
CheckBoxComponents[0].check();  // Checks first checkbox
CheckBoxComponents[0].unCheck();  // Unchecks first checkbox
```
