### ISSUE TITLE
What is a "Pane" and how to use it?

### ISSUE THREAD

**Issue by ielcoro** [OfficeDev/office-ui-fabric-js#189]
I´m looking for a "panel" (in bootstrap terms), however the Fabric builtin "ms-Panel" is a floating component that can go on the left or right and starts hidden. What I´m looking for is a panel that sits in place, used for separating content.

In the [documentation of ms-Panel](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Panel.md) I found this: 

>  For containers used for complex tasks that requires context, use a separate Pane alongside the existing experience such as a List/Details layout

However I can't found a component called "Pane" and I tried with ms-Pane class and fabric["Pane"] without success. How I can use "a separate Pane"?

**Comment by mikewheaton** [comment]
Unfortunately we don't have a Pane component right now. I've added a [card on Trello](https://trello.com/c/0c9EZw1a) to track this request.
