### ISSUE TITLE
Issue: Dropdown longer texts are trimmed out of view 

### ISSUE THREAD

**Issue by echoworxdev** [OfficeDev/office-ui-fabric-js#196]
Hi there,
I am using OfficeUIFabric Core 5.0.0 with with OfficeUIFabricJS 1.2.0 for building an Office365 add-in.

The Dropdown component trims longer texts out of the view as shown below:
![image](https://cloud.githubusercontent.com/assets/23174758/20367694/9699b652-ac1e-11e6-8509-7b02f4b839b4.png)
Kindly look into it.
Thank you

**Comment by leddie24** [comment]
Hi @echoworxdev , I'm having difficulty reproing this bug.  Can you post some example code or a codepen possibly?

**Comment by echoworxdev** [comment]
Hi there,
Thanks for the immediate response. 
I forgot to mention, this happens only when the screen is resized to  smaller size.

Below is the code snippet and a screenshots. 

` <div id="mydDown" class="ms-Dropdown" tabindex="0">
        <label  class="ms-Label">Dropdown label</label>
        <i class="ms-Dropdown-caretDown ms-Icon ms-Icon--ChevronDown"></i>
        <select id="myselect" class="ms-Dropdown-select">
            <option>This is a really long text that demonstartes the problem I am facing.</option>
            <option>Thank You</option>           
        </select>
    </div>    `

Normal Screen:
![image](https://cloud.githubusercontent.com/assets/23174758/20394314/1700eb42-acad-11e6-9323-b16a854ea2ab.png)

Smaller Screen:
![image](https://cloud.githubusercontent.com/assets/23174758/20394416/6fa374f4-acad-11e6-96c2-819546565cdf.png)

P.S: It is preferable try the code snippet in Compose Mode to better understand the glitch.

**Comment by ericthompson** [comment]
Thanks for the extra detail, @echoworxdev!

We've chatted with some of our Designers and [the usage guidance for the control](http://dev.office.com/fabric#/components/dropdown) asks for using "shortened statements or words" implying that long strings don't make for the best options in the dropdown.

In this case, we'd recommend avoiding using long strings. Radio buttons would be much better suited, since the text can wrap to multiple lines.

**Comment by ericthompson** [comment]
As I was typing, @leddie24 was building a perfectly suitable fix 👍 

It's now merged and allows the dropdown to truncate at the ends in the event of a long string. Good work @leddie24!
