### ISSUE TITLE
Missing instructions to add script reference to fabric.min.js from CDN

### ISSUE THREAD

**Issue by vishiy** [OfficeDev/office-ui-fabric-js#197]
When we deploy 1.2.0 version of fabric js to CDN, we need to ensure that we update instructions to include/add script reference to minified fabric js from CDN location

**Comment by Reezaali** [comment]
Also I cannot find fabric.min.js on the CDN. Can you confirm that it is deployed?

**Comment by vishiy** [comment]
https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js
https://spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.js

I see both for 1.2.0.

**Comment by mikewheaton** [comment]
Those links above are for the testing server, and not the production location. The production URLs will be:

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css

The files are checked into the testing server (as @vishiy confirmed above) but have not yet been deployed to production.

**Comment by Jahnp** [comment]
This is fixed now. Closing!
