### ISSUE TITLE
MessageBanner: wrong CSS class for chevrons in fabric.js

### ISSUE THREAD

**Issue by FSc21** [OfficeDev/office-ui-fabric-js#205]
Hey,

I was trying to use the MessageBanner component (https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/MessageBanner.md). When clicking on the ChevronDown icon however, the icon completely disappeared. Collapsing the text unfortunately did not bring brack the icon either. In the fabric.js file I found out that the CSS icon names are not correctly set in the _expand and _collapse functions. Please update either the icon names in the current fabric.css file or in the functions of the current fabric.js file.
Thanks!
<img width="513" alt="chevrons_fabric js" src="https://cloud.githubusercontent.com/assets/23665008/20539849/e27f5fe0-b0f6-11e6-9fd7-e176b0426c66.png">
`fabric.js version 1.2`

<img width="266" alt="chevrons_fabric css" src="https://cloud.githubusercontent.com/assets/23665008/20539852/e627c128-b0f6-11e6-8a74-17dd46e2c7c8.png">

`fabric.css version 4.0`

**Comment by mikewheaton** [comment]
Thank you for identifying this bug, @FSc21. It looks like we missed this change when the new set of icons was added to Fabric JS. If you'd like to submit a pull request we can get this fix merged in.

**Comment by ericthompson** [comment]
Looks like this was fixed with #206 - closing!
