### ISSUE TITLE
Button is-disabled documentation needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#214]
Hi, can we clarify, with code snippets, how the is-disabled class should be used on a button? 

Thanks.

**Comment by Reezaali** [comment]
Or should this be set using a method on the component?

**Comment by leddie24** [comment]
@Reezaali.  Component states are classes (or attributes sometimes) that are applied to elements.  Our new website should be updated to explain this more clearly.  Here's an excerpt from Button that explains the is-disabled class

> When using an `<a>` element, apply this class to disable the button. When using a `<button>,` the disabled attribute can be used instead.

Example would be 

`<button class="ms-Button" disabled>
  <span class="ms-Button-label">Create Account</span> 
</button>`

`<a class="ms-Button is-disabled">
  <span class="ms-Button-label">Create Account</span> 
</a>`
