### ISSUE TITLE
Breadcrumb overflow issue

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#217]
Hello, the breadcrumb component does not expand and contract automatically when the screen size changes. Thanks!

**Comment by wdo3650** [comment]
@Reezaali thanks for noting this. PR #188 should have fixed the bug. Check out master for the update.

**Comment by Reezaali** [comment]
Leave a comment

**Comment by Reezaali** [comment]
I updated to use the following CDN links and I still see the problem:

` <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.min.css">
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css">
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>
`

**Comment by wdo3650** [comment]
The fix is in master so it isn't in the latest release. The next release should have it.
