### ISSUE TITLE
Callout code in README does not work

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#224]
Hello, I've followed the steps in the README for the callout component. I see the button. When clicked, nothing happens. Can you please review and update the code/documentation please? Thanks!

Also, callout code uses the class "ms-Callout-subText--" which looks like a mistake. Please confirm. Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali .  The updated documentation's code snippets should fix this error as well as the ms-Callout-subText-- class also.
