### ISSUE TITLE
Dialog documentation does not work and formatting fix needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#225]
Hello, I've followed the steps in the README for the dialog component and nothing is shown. Can you review the documentation / code and update please? 

Also, the last code block needs to be formatted correctly.

Thanks!

**Comment by tarjeieo** [comment]
Seeing the same thing. The javascript snippet does not set the correct display-rules on the dialog, and the dialog isn't shown as the css-class has display:none.

**Comment by leddie24** [comment]
This should be fixed with the newest documentation updates.  Please pull from master and see if this solves your issue, thanks!
