### ISSUE TITLE
Some styles are not applied for button types

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-js#228]
Button's type specific css styles are not works after the changeset:
[Reduce specificity of button modifiers](https://github.com/OfficeDev/office-ui-fabric-react/commit/e20fd424fb278fa090cddb6417915a47a83024cf) 
They are overriden by ms-Button class.

![capture](https://cloud.githubusercontent.com/assets/4600781/20761076/7e69c8e4-b72a-11e6-9a8b-5b067f955427.PNG)

**Comment by mikewheaton** [comment]
The [changes you linked to](https://github.com/OfficeDev/office-ui-fabric-react/commit/e20fd424fb278fa090cddb6417915a47a83024cf) are in the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/) project. Are you using Fabric React or Fabric JS?

**Comment by biogenez** [comment]
Sorry. I will recteate it in the office-react-ui repository.
