### ISSUE TITLE
Command bar initialization issues

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#231]
Hello,

<img width="383" alt="commandbar" src="https://cloud.githubusercontent.com/assets/9439288/20773144/487fee04-b705-11e6-884a-c32114496575.PNG">

When using the code in **Using this component**, there appears to be several initialization issues, which are listed below:

- Is the black outline on click intentional?
- When clicking the New command button, no dropdown menu appears. Can you please fix and provide code that shows how to achieve this?
- The 4th command button text is being truncated. 
- The 5th button is right aligned.

Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali.  Can you pull from master and try using the sample code again?  Our new documentation should fix this, and show an example component as well with your issues solved. 

The 5th button is inside of the .ms-CommandBar-sideCommands container, which shows all commands as right-aligned by default.
