### ISSUE TITLE
Contextual menu documentation updates needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#233]
The code in **Using this component** does not work as expected. I see the button but clicking on it does nothing. Can you provide updated sample code please?

Also, can you provide additional documentation on how to use:
- Variants
- States
- Optional functionality.

Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali.  Our new documentation should solve this issue.  If you're still experiencing problesms with the new updated code snippets, please re-open.
