### ISSUE TITLE
Dropdown documentation update needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#234]
The code in **Using this component** does not work as expected. I see the component with no outline (which is difficult to see on a white background), and clicking on the down chevron does not show the menu items. 

Please also include documentation on variants and states.

**Comment by leddie24** [comment]
Hey @Reezaali.  Our new JS site should have better documentation on using this component.  If the updated code snippets are still not working as expected please re-open.
