### ISSUE TITLE
Facepile issues

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#236]
I followed the code in **Using this component**. I see the facepile, however I also see the persona card when the page loads i.e. before I click anything. Is this the intended behavior, or should the persona card be hidden at first?

Also, when I click on a circle on the Facepile, nothing happens. I was expecting the persona card to change. Can you please provide updated sample code to show how this can be achieved?

Thanks!

**Comment by leddie24** [comment]
@Reezaali , this should be fixed with the new documentation changes. Can you see the new FacePile code snippets and see if that solves your issue?
