### ISSUE TITLE
MessageBanner initialization code or component issue

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#239]
I used the code in **Using this component** and noticed that the text does not overflow. 

<img width="165" alt="messagebar" src="https://cloud.githubusercontent.com/assets/9439288/20776948/7f8cbe82-b718-11e6-872e-7e7ed57ad7fa.PNG">

**Comment by ericthompson** [comment]
Closing this as it appears to be a dupe of #240.
