### ISSUE TITLE
ProgressIndicator documentation needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#250]
Hello, following the code in **Using this component** shows an indicator that is static i.e. the progress indicator does not show progress. Can you provide documentation on how this can be achieved please? Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali.  Our progress indicator has several component methods that will provide the functionality to show progress.  The new documentation provides these component methods.


Below is a code snippet on how to use them

```
var ProgressIndicatorElement = document.querySelector(".ms-ProgressIndicator");
var ProgressIndicator = new fabric['ProgressIndicator'](ProgressIndicatorElement);
ProgressIndicator.setProgressPercent(.25); // Sets Progress to 25%
ProgressIndicator.setProgressPercent(.5); // Sets Progress to 50%
ProgressIndicator.setProgressPercent(1); // Sets Progress to 100%
```

<img width="1061" alt="screen shot 2017-01-24 at 2 25 21 pm" src="https://cloud.githubusercontent.com/assets/1291968/22269608/f7101118-e240-11e6-8a05-42b5fa53140f.png">
