### ISSUE TITLE
Spinner documentation update needed

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#252]
Hello, following the steps in **Using this component** does not work as expected. No spinner is shown on my page. Can you please review and update as necessary? Thanks!

**Comment by leddie24** [comment]
Hi @Reezaali.  Can you try again with the new documentation code snippets?  Please re-open if you're still experience this issue.

**Comment by mvpkenlin** [comment]
I following the same code as shown in https://dev.office.com/fabric-js/Components/Spinner/Spinner.html

No spinner is shown neither the label. I checked the html code and found the required html was generated and the opacity is keep changing.
