### ISSUE TITLE
Can't disable Checkbox?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-js#253]
Using the sample markup/code from https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/CheckBox.md, if I add the "disabled" attribute to the Input element, nothing happens.  The checkbox is still enabled.  I've tried just the attribute name and "disabled = 'disabled'"

'Checked' attribute works.

**Comment by mikewheaton** [comment]
Looks like we have the same issue here: [Disabling checkboxes](https://github.com/OfficeDev/office-ui-fabric-js/issues/186)

Can you try adding the `is-disabled` class?

**Comment by manndave** [comment]
OK, sorry I missed that when I looked at the open issues.  

Here's what I get...adding the `is-disabled` class to the **label** will disable the control and the label.  Nothing else seems to work.  This is fine by me so long as something works, but it is a little odd as I think people would expect the class to be added to the control and not the label, but still have it disable both.

**Comment by mikewheaton** [comment]
If I recall, the actually `<input type="checkbox">` that is used is just there for accessibility. It's hidden from view, and the actual checkbox that you see is an `::after` pseudo-element. This gives us full control over the styling, but it's not intuitive from a developer perspective.

We're working on an improved documentation site that will cover all of this – thanks for hanging in there! Please continue to open issues as you encounter difficulties.
