### ISSUE TITLE
Documentation's index.html (in 'dist') has broken paths

### ISSUE THREAD

**Issue by stewartadam** [OfficeDev/office-ui-fabric-js#254]
`dist/documentation/index.html` as well as each of the HTML files in `dist/documentation/Getting Started` have incorrect paths to the CSS files, resulting in unreadable documentation from both:
1. The ZIP downloads included as a part of the project's releases
2. Opening `dist/documentation/index.html` after running `gulp`

The problem is that `demo.css` is not in the parent folder `dist`, but rather inline with `index.html` in the folder of `dist/documentation`:
```
    <link rel="stylesheet" href="../demo.css">
	<link rel="stylesheet" href="../css/fabric.min.css">
	<link rel="stylesheet" href="../css/fabric.components.min.css">
```
(side note: also note the mixed spaces/tabs for indentation)

**Comment by Jahnp** [comment]
This will be fixed with the most recent documentation updates. We'll revisit this and verify once those bits have been merged to master. Thanks for reporting this @stewartadam!

**Comment by leddie24** [comment]
Hi @stewartadam.  These paths should be updated in the new documentation.  Pull from master if you're on an outdated branch.
