### ISSUE TITLE
Full documentation is not readily available online

### ISSUE THREAD

**Issue by stewartadam** [OfficeDev/office-ui-fabric-js#255]
The local docs are built as HTML pages, so it would be easy to publish them. As best I can tell, they are currently not made available online through this repo nor the Fabric JS website.

Since the local docs (even the ones in `dist` after building) cannot be opened directly in a browser (see #126; #254) and the same issues apply to the ZIP downloads available from the Releases page, users are therefore forced to source necessary prerequisite software for the build and follow the steps for a local build just to read the documentation.

IMO that's an unnecessary high barrier of entry for new users who may not know how to set that up easily, and a delay for users who know how but just want to get at the docs or examples.

The markdown documentation is readily available online, but I see two issues with it currently:
1. There are two sources of truth (local/md), and the md docs appear to lag behind (e.g. see #28) - I'm not sure how the local -> md doc process happens, but ideally it would be automatic and immediate so information is available in both places at all times.
2. The local docs have a major advantage over md which is that they're interactive!

**Comment by battletoilet** [comment]
Hey @stewartadam, we totally agree with this feedback. We are currently working on converting over our markdown src files to just plain HTML and outputting a flat html website so that it's pretty easy to view in the browser. This work has already started so hopefully we will have an update soon.

**Comment by stewartadam** [comment]
That's great to hear!

**Comment by leddie24** [comment]
This should be fixed with our new documentation changes.
