### ISSUE TITLE
Release 2.6.3 to fix Dropdown on mobile

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/office-ui-fabric-js#261]
Per comment by @mikewheaton in https://github.com/OfficeDev/office-ui-fabric-core/issues/552#issuecomment-266489767, can the CSS for the DropDown component in release 2.6.2 be updated to include the mobile rendering / issue where the control jumps when the browser is <480px?

This fix was added to the Fabric Core in https://github.com/OfficeDev/office-ui-fabric-core/issues/552

It's causing issues for the ngOfficeUIFabric which is still MDL1 & based on 2.6.2.

**Comment by mikewheaton** [comment]
Apologies for the delay here. We're running at full speed again after the holidays and I'm aiming to get this done next week.

**Comment by mikewheaton** [comment]
Thank you for your patience; this took much longer than expected to get to. I've published [Fabric 2.6.3](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.3) with a fix to the Dropdown component on mobile. It's available via GitHub, NPM, and Bower now, and should be on the CDN within a week.
