### ISSUE TITLE
Autocomplete on the Search Box

### ISSUE THREAD

**Issue by SharePointRadi** [OfficeDev/office-ui-fabric-js#263]
Are you planning to create autocomplete / autosuggestion capabilities on the search box?

**Comment by SharePointRadi** [comment]
I found more info on the http://dev.office.com/fabric#/components/searchbox page. But here there's not much info that this feature exists: https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/SearchBox.md

**Comment by Reezaali** [comment]
@SharePointRadi - thanks for the feedback. Can you tell us what additions we should make to the page above please? Feel free to reopen the issue. Also, if you want to make the changes and submit a pull request, the team will review it and accept it. Thanks!

**Comment by luubinhan** [comment]
A auto-complete component like this one https://ant.design/components/auto-complete/ could be helpful

**Comment by cythomli** [comment]
@SharePointRadi Any updates on this? Plz let me know.
