### ISSUE TITLE
Debug documentation

### ISSUE THREAD

**Issue by seriewe** [OfficeDev/office-ui-fabric-js#264]
Can you please provide a documentation how to set up VS-Code to generate source-maps and debug the Components while running inside the "gulp-server" on localhost. 
Or are there already an existent doc on how to debug the components?

**Comment by Jahnp** [comment]
Hey @seriewe, thanks for the suggestion. I've added this as a [feature request to the Trello board](https://trello.com/c/AbzN6hFq)--please go ahead and vote and we'll revisit this request in a future sprint.
