### ISSUE TITLE
Hero Button hover & active states unnoticeable

### ISSUE THREAD

**Issue by jedunn** [OfficeDev/office-ui-fabric-js#267]
The hero button has a very subtle hover and active state. Is there a variant with more pronounced effects? Does this meet accesibility requirements?

**Comment by Jahnp** [comment]
Closing this issue for now. After some discussion, we've decided that the Hero button is a good candidate for removal from Fabric JS, since it's also being removed from Fabric React. If you'd like to use a more clearly accessible button, consider using a Primary button instead.
