### ISSUE TITLE
Panel: Page can scroll while PanelHost is open

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#27]
_From @battletoilet on June 22, 2016 18:51_

If the page goes beyond the screen size and Panel is opened, PanelHost does not stop the screen from scrolling and causes the panel to stay at the top of the screen. See screenshot below.
![image](https://cloud.githubusercontent.com/assets/622498/16279390/9fd19d5c-386f-11e6-8154-43e851e88595.png)

_Copied from original issue: OfficeDev/office-ui-fabric-core#683_

**Comment by mikewheaton** [comment]
_From @lixonic on June 27, 2016 4:18_

similar behaviour in overlay too.  
![image](https://cloud.githubusercontent.com/assets/934220/16368474/4bc460ec-3c4c-11e6-82ad-f13da52e957d.png)

**Comment by leddie24** [comment]
Should be fixed now,  this is addressed in PR #83 (still waiting approval)
