### ISSUE TITLE
How in the world do you use Dialogs?

### ISSUE THREAD

**Issue by cnswico** [OfficeDev/office-ui-fabric-js#275]
The details included in the [documentation](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Dialog.md) contain only the Office Fabric Dialog HTML-CSS structure and JS instantiation. It doesn't include **how to trigger the dialog**. To make things worse, there is absolutely _no useful documentation_ around the internet ([this](https://codepen.io/andrewconnell/pen/gaLqXP) one is no help either).

_How do you use the Dialogs?_

**Comment by mikewheaton** [comment]
Sorry for the frustration here, @cnswico. We've recently gone through and updated the documentation with working examples (rather than the GitHub docs you see now) and are in the process of getting the website online. In the meantime, you can [clone and build the docs locally](https://github.com/OfficeDev/office-ui-fabric-js#clone-build-and-view-the-docs).

**Comment by Reezaali** [comment]
@cnswico - some of the components have functions. The dialog has the open and close method. The code below shows you how to use it. Basically you keep a reference to the dialog after initializing it, and then call the function you need on the component. Look at the Dialog's TS link below to see the methods defined on the Dialog component. As @mikewheaton indicated, updated documentation is coming soon. 

Hth,
Reeza.

`  var DialogElement = document.querySelector(".ms-Dialog");
            var dialogComponent = new fabric['Dialog'](DialogElement);
            dialogComponent.open();`

[Dialog TS source file](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/src/components/Dialog/Dialog.ts)

**Comment by Jahnp** [comment]
Indeed, to pile on @mikewheaton and @Reezaali's points, this will be addressed with the updated documentation site. We'll follow up here when it's ready. 

In the meantime, here's a pen with a sample from the new Dialog documentation that I think you'll find helpful:
http://codepen.io/jahnp/pen/MJpgNL
