### ISSUE TITLE
Breadcrumb Navigation and keypress event handling.

### ISSUE THREAD

**Issue by Hardhik** [OfficeDev/office-ui-fabric-js#279]
When the focus is on one of the breadcrumb's elements and we press alt+right OR alt+left the default behavior should be that of the browser ( navigate forward OR backward in history).
This is not honored currently. Can be seen here too:
http://dev.office.com/fabric#/components/breadcrumb#Variants

I guess the problem is in the keypress event handler where we stop the propagation of keypress events. We might want to allow for propagation in scenarios where modifier keys(alt, shift, ctrl) are present.

**Comment by Jahnp** [comment]
Hey @Hardhik, thanks for filing this! This is a great catch. However, the sample you linked appears to be for the [Fabric React Breadcrumb](http://dev.office.com/fabric#/components/breadcrumb) component, however, not the [Fabric JS one](https://dev.office.com/fabric-js/Components/Breadcrumb/Breadcrumb.html). The Fabric JS Breadcrumb does not currently support arrow-based keyboard navigation, so this shouldn't be an issue there.

Would you mind re-opening this issue [there](https://github.com/OfficeDev/office-ui-fabric-react/)? I'll go ahead and close this in the meantime. Thanks again!
