### ISSUE TITLE
MessageBanner: Document/implement showing and hiding

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#28]
_From @Rick-Kirkham on June 22, 2016 0:11_

The JS version of MessageBanner exposes a hideBanner() method. This is not exposed in the TypeScript verson. As a result the only way that the MessageBanner can be hidden on startup, which is normally what a developer would want, is to add the class "is-hidden" to the <div> with ms-MessageBanner class. But the MessageBanner.hbs file that is included does NOT do this. Also, there could be scenarios, other than startup, when calling code will need to hide a MessageBanner. I _think_ you just have to change 
private _hideBanner():
to
public hideBanner():

_Copied from original issue: OfficeDev/office-ui-fabric-core#680_

**Comment by mikewheaton** [comment]
Thanks for reporting this, @Rick-Kirkham. Showing and hiding a MessageBanner is essential functionality. We'll take a look at the JS and make sure that our documentation clearly shows how to accomplish this.

**Comment by ericthompson** [comment]
This is now included in the localhost docs - closing for now.
