### ISSUE TITLE
Components - Table - Selection causes issues

### ISSUE THREAD

**Issue by austin-best** [OfficeDev/office-ui-fabric-js#281]
When using a "ms-Table--selectable" table:

Drag-selecting text and ending somwhere in tbody creates an issue where the table seems to destroy itself.

If the drag-selection ends in the thead, then table table size expands outside of his original parent.

![fabric-table-selection](https://cloud.githubusercontent.com/assets/22735659/22434298/b7452c52-e6d8-11e6-9ba2-214dd66cfd37.gif)

![fabric-table-selection2](https://cloud.githubusercontent.com/assets/22735659/22434441/49b42a02-e6d9-11e6-8d73-2a8183d0cdcd.gif)

**Comment by Jahnp** [comment]
Thanks for reporting this, @austin-best! 

We reproed on the [documentation site](https://dev.office.com/fabric-js/Components/Table/Table.html). This is a pretty nasty issue and we'll investigate.
