### ISSUE TITLE
1.3.0 ChoiceFieldGroup LI artifacts and not firing events

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/office-ui-fabric-js#291]
Using the example from:

https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/ChoiceFieldGroup.md

But it displays the LI bullets, I can switch options (the UX changes) but  non of the events I stick on fire

Question: How to interact with these (the Checkboxes I use work fine)

![](http://i.imgur.com/SxtN9wY.jpg)

```
<div class="ms-ChoiceFieldGroup" id="choicefieldgroup" role="radiogroup" style="margin-left:3em"
         onchange="console.log(23);">
        <ul class="ms-ChoiceFieldGroup-list">
            <li class="ms-RadioButton">
                <input type="radio" class="ms-RadioButton-input" onclick="console.log(22);">
                <label role="radio" class="ms-RadioButton-field" tabindex="0"
                       aria-checked="true" name="choicefieldgroup">
                    <span class="ms-Label">Option 1</span></label>
            </li>
            <li class="ms-RadioButton">
                <input tabindex="-1" type="radio" class="ms-RadioButton-input">
                <label role="radio" class="ms-RadioButton-field " tabindex="0"
                       aria-checked="false" name="choicefieldgroup">
                    <span class="ms-Label">Option 2</span></label>
            </li>
            <li class="ms-RadioButton">
                <input tabindex="-1" type="radio" class="ms-RadioButton-input">
                <label role="radio" class="ms-RadioButton-field is-disabled" tabindex="0"
                       aria-checked="false" name="choicefieldgroup"
                       aria-disabled="true">
                    <span class="ms-Label">Option 3</span></label>
            </li>
            <li class="ms-RadioButton">
                <input tabindex="-1" type="radio" class="ms-RadioButton-input">
                <label role="radio" class="ms-RadioButton-field" tabindex="0"
                       aria-checked="false" name="choicefieldgroup">
                    <span class="ms-Label">Option 4</span> </label>
            </li>
        </ul>
    </div>

```

**Comment by Reezaali** [comment]
Hi @Danny-Engelman. I've found a solution to this by using jQuery.

Here's a link: https://github.com/OfficeDev/Excel-Add-in-JavaScript-SalesTracker/blob/master/SalesTrackerWeb/Scripts/Home.js#L72-L81

Thanks!
Reeza.

**Comment by Jahnp** [comment]
Thanks @Reezaali! 

@Danny-Engelman, thanks for reporting this. We realize that there are cases in Fabric JS where there is not a method to return a component's value, such as CheckBox's `getValue`. While adding those methods is the right thing to do, we can't guarantee a timeline for doing so. In the absence of those methods, you can always use vanilla JavaScript to extract an `input`'s value, which is what @Reezaali's sample demonstrates.

As for the list bullets showing up, that should have been addressed with #285. If you have a local clone of Fabric JS, try pulling the latest and let us know if you still see the list bullets. I'm not seeing them on the Fabric JS website, which has the latest as of 1.4.0:
![image](https://cloud.githubusercontent.com/assets/307118/23079579/5f496f30-f502-11e6-9d4e-f21da7477cc1.png)

I'll go ahead and close this issue for now, but please feel free to re-open it if this doesn't address your questions.

**Comment by Danny-Engelman** [comment]
Yes the LI bullets are gone when I load 1.4.0

But, the question remains why none of the Radio button events fire.
I added them in HTML, I tried adding with addEventListener
The FabricJS Radio buttons fire no events

The FabridJS Checkboxes I now use work just fine.

https://365csi.nl/toolkit/iconator.html

I added the not working Radio buttons to test:

![](http://i.imgur.com/gSybcaE.jpg)

tnx

**Comment by Reezaali** [comment]
Hi @Danny-Engelman - I wonder if you're experiencing this problem: https://github.com/OfficeDev/office-ui-fabric-js/issues/195

The link you sent does not open up a page looking like your screenshot. 

Thanks!
Reeza.

**Comment by Danny-Engelman** [comment]
https://365csi.nl/toolkit/iconator.html

Uses ES6, CSS4 and HTML5 not supported yet bij IE or Edge.. I do R&D in Chrome

I dug in a bit deeper...

![](http://i.imgur.com/lDiyvaz.jpg)

made visible with CSS:

```
        .ms-RadioButton,
        .ms-RadioButton-input {
            border: 1px dashed green;
            background: lightgreen;
            cursor: pointer;
        }

        .ms-RadioButton-input {
            position: absolute;
            opacity: 1;
            margin-left: -1em;
            zoom: 2;
            z-index:1;
        }

        .ms-RadioButton-field {
            outline: 1px dashed lightcoral;
            background: lightcoral;
        }
```

### Analysis

The (grey) native RadioButtons work but do not fire Fabric events (ofcourse)

The green area triggers the click handler I put on the LI (but doesn't fire Fabric)

Red Fabric elements get Fabric events on initialisation but don't propagate to my own event handlers because
https://github.com/OfficeDev/office-ui-fabric-js/blob/master/src/components/RadioButton/RadioButton.ts
has 
```    private _RadioClickHandler(event: MouseEvent): void {
      event.stopPropagation();
      event.preventDefault();
      if (!this._choiceField.classList.contains("is-disabled")) {
        this._dispatchSelectEvent();
      }
    }```

Radio buttons are the only elements that use a Global CustomEvent function.

If you overload it in the Dev console with:

```CustomEvent=function(a,b){console.log(a,b,this);}
```

You see the events happening

It is possible to hook into that event (most likely in better ways) with:

```
document.addEventListener("msChoicefield", function(event){
    console.log(event);
    var radioButtonInput=event.srcElement.previousSibling;
    console.info(radioButtonInput);
}, false);
```

But it will fire 2 equal events for one click

Because FabricJS assigns 2 click events (both dispathing to the msChoicefield event on the document

![](http://i.imgur.com/1j8Zcmu.jpg)

**Comment by Danny-Engelman** [comment]
Double events is my mistake.. had a nested class ms-ChoiceFieldGroup.. so fabric init code ran twice

**Comment by Danny-Engelman** [comment]
To hook into the custom FabricJS msChoiceField event (which adds a detail object on the event, with the group name)

```
document.addEventListener("msChoicefield", function (event) {
    let radioButtonPressed = event.srcElement;
    //do something for pressed button
    [].map.call(document.querySelectorAll("label[name='" + event.detail.name + "']"), function (radioButton) {
        if (radioButton !== radioButtonPressed) {
            //do something for other buttons
        }
    });
}, false);

```

**Comment by zamol** [comment]
I have the same problem as the one described above, the radio buttons in Fabric JS does not fire on a change or click event. The event would have displayed or removed out of sight certain divs, based on the user choices.

Is there any solution to this problem or I need to use check-boxes or command buttons instead?

Thanks!
