### ISSUE TITLE
Content grouping (Accordion)

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#30]
_From @git-sdavidpaul on September 16, 2015 1:40_

Is there any components (current or upcoming) for grouping content? something like Accordion panels etc. or some other intuitive controls for grouping content under some common entities.

_Copied from original issue: OfficeDev/office-ui-fabric-core#128_

**Comment by mikewheaton** [comment]
_From @ericthompson on September 16, 2015 15:34_

Looking into this!

**Comment by mikewheaton** [comment]
We're working on an accordion for use within a panel. It's not yet clear when this will be made available as a Fabric component.

**Comment by mikewheaton** [comment]
We've assigned this to a designer.

**Comment by ericthompson** [comment]
Closing as this component request is now [tracked on the Fabric JS Trello board](https://trello.com/c/xac3eI2u/33-accordion-component).

**Comment by patrickabel** [comment]
What's the status on this component request? Based on the Trello board it looks like it's in the queue, but I wasn't sure given no items are currently "in development."

**Comment by Stanley-Jovel** [comment]
I would also like to know the status on this, it seems it hasn't been worked on since 2016
