### ISSUE TITLE
importing normal fabric js in sp framework, and what is the actual latest version of fabric?

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/office-ui-fabric-js#313]
What is the actual process of importing fabricjs to sharepoint framework? I would like to import the normal fabricjs to my angular based application instead of using office-fabric-react components. 

Is there also any typings available for normal fabric js?

Thanks

**Comment by jonathanhotono** [comment]
Ah. I found the answer.
Simply set the following configuration:

On webpart ts file:
![image](https://cloud.githubusercontent.com/assets/6864547/24453229/bd2c4baa-14d2-11e7-9a17-058a015c078a.png)
on config.json:
![image](https://cloud.githubusercontent.com/assets/6864547/24453256/d39c4f34-14d2-11e7-89d9-a51abd1756f0.png)
on the controller, simply expose the fabric using [require](url).
![image](https://cloud.githubusercontent.com/assets/6864547/24453277/eb8398be-14d2-11e7-8a5a-6995b2817ef0.png)

**Comment by Danny-Engelman** [comment]
Note that 1.2.0 is rather old... 1.4.0 is current

Also be aware FabricJS is distributed on FabricCore 5.0.1 , but does work with FabricCore 5.1.0 and 6.0.0

Once you update to FabricCore 6.0.0 you need to update all the classnames;
as Microsoft made a breaking change: all ``ms-u-`` are now ``ms-`` (see the releasenotes)

**Comment by jonathanhotono** [comment]
Thanks @Danny-Engelman .. I'm confused on the separation of FabricCore and FabricJS. I also found another package called Office-ui-fabric. 
![image](https://cloud.githubusercontent.com/assets/6864547/24478397/662ca198-1526-11e7-89a1-d68c6369d6b6.png)

Does Office-ui-fabric combines both FabricCore and FabricJS?

**Comment by Danny-Engelman** [comment]
You are not the only one confused, I think everyone is, including developers.

There is:

* Fabric Core : https://github.com/OfficeDev/office-ui-fabric-core

Then on top of that are

* Components for (plain) JavaScript: https://github.com/OfficeDev/office-ui-fabric-js
* Components for Angular: https://github.com/ngOfficeUIFabric/ng-officeuifabric
* Components for React: https://github.com/OfficeDev/office-ui-fabric-react

The Components make your life easier, but are not required to work with Fabric Core  
You pick **one** of these 3 to work with (technically they can all co-exist.. I think)

<hr>
### Fabric Components JavaScript : office-ui-fabric-js

FabricJS Documentation mentions old FabricCore release numbers, 
and Fabric Core 6.0.1 mentioned as latest release is not on their CDN 

```
//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js
```

work fine for me (*be aware 6.0.0 made breaking changes in the className prefix*)

### Versions

There was no jump from 2.6.3 to 6.0.0, 

Scroll down that page and you see that the sort order is by Modification time, NOT release number  

Microsoft is maintaining and patching **multiple** versions

Current versions Fabric Core are:

5.0.0 ► 5.0.1 ► 5.1.0 ► 6.0.0 ► (6.0.1)

Note that [6.0.1](//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.1/css/fabric.min.css) is **not** on the CDN yet:

[//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.1/css/fabric.min.css](//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.1/css/fabric.min.css)

### Sync / Current

Don't sync/download/npm/copy/include/import files

Reference the files on the Microsoft CDN

```
//spoprod-a.akamaihd.net/files/fabric/office-ui-fabric-core/6.0.0/css/fabric.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css
//static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js
```

**Comment by jonathanhotono** [comment]
Thanks for the clarification @Danny-Engelman ..

I'm just trying to make office-fabric-js to coexist with office-fabric-react as I got certain apps that are ported to the new spfx on classic page that is using office-fabric-js dialog box, and there are also newer apps/webparts written in office-ui-fabric-react combined together in a page. I can confirm that office-fabric-js and office-fabric-react doesn't quite coexist with each other :(

Raised the issue to sp dev docs:
https://github.com/SharePoint/sp-dev-docs/issues/536
