### ISSUE TITLE
How to implement autocomplete on the SearchBox (React Component)

### ISSUE THREAD

**Issue by pradeemi** [OfficeDev/office-ui-fabric-js#320]
Its mentioned in official web site (Below) that we can use "AutoSuggest", but no property available to implement the same.
https://dev.office.com/fabric#/components/searchbox.

Please let me know the answer on priority...

**Comment by Jahnp** [comment]
Hey @pradeemi, just checking, is this meant for Fabric JS (this repo) or [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/)? If the latter, would you mind closing this issue and re-opening there? 

It is a bit funny you should ask this now--there have been conversations going on within the last few days about adding this exact functionality to the React SearchBox, though timelines haven't been discussed. I'd definitely expect this feature to land there before Fabric JS, however--most of our investments are focused there at the moment.

**Comment by pradeemi** [comment]
Its about "Fabric React".

**Comment by Jahnp** [comment]
Thanks. If you don't mind, I'll go ahead and close this here--would you mind re-opening this in Fabric-React so we can track this in the right repo?
