### ISSUE TITLE
Initialize with a selected option

### ISSUE THREAD

**Issue by sevenam** [OfficeDev/office-ui-fabric-js#331]
Issue [#33](https://github.com/OfficeDev/office-ui-fabric-js/issues/33) was re-introduced with release 1.3.0 and the "_checkTruncation" method.

Unable to populate the dropdown with the `selected` attribute set.

**Comment by sevenam** [comment]
As far as I can see, adding the following statement to the constructor of `Dropdown.ts` should fix it:

`if(option.selected) {
	newItem.classList.add(IS_SELECTED_CLASS);
}`

**Comment by Jahnp** [comment]
Closing this since #332 should have fixed the issue. Thanks @sevenam!

**Comment by SSPO** [comment]
Found a work around when calling Fabrics:
        var DropdownHTMLElements = document.querySelectorAll('.ms-Dropdown');
        for (var i = 0; i < DropdownHTMLElements.length; ++i) {
            var Dropdown = new fabric['Dropdown'](DropdownHTMLElements[i]);
            
            _if(DropdownHTMLElements[i].querySelectorAll('option:checked').length==1){
                var selectedValue = DropdownHTMLElements[i].querySelectorAll('option:checked')[0].value
                $(DropdownHTMLElements[i]).find($('li:contains("'+selectedValue+'")')).addClass("is-selected")
                $(DropdownHTMLElements[i]).find($('.ms-Dropdown-title')).text(selectedValue);
            }_
        }

**Comment by SSPO** [comment]
Find a work around when initializing Fabrics:

        var DropdownHTMLElements = document.querySelectorAll('.ms-Dropdown');
        for (var i = 0; i < DropdownHTMLElements.length; ++i) {
            var Dropdown = new fabric['Dropdown'](DropdownHTMLElements[i]);
            
            if(DropdownHTMLElements[i].querySelectorAll('option:checked').length==1){
                var selectedValue = DropdownHTMLElements[i].querySelectorAll('option:checked')[0].value
                $(DropdownHTMLElements[i]).find($('li:contains("'+selectedValue+'")')).addClass("is-selected")
                $(DropdownHTMLElements[i]).find($('.ms-Dropdown-title')).text(selectedValue);
            }
        }
