### ISSUE TITLE
why Fabric js use a very old Fabric core

### ISSUE THREAD

**Issue by cmk128** [OfficeDev/office-ui-fabric-js#349]
why Fabric js use a very old Fabric core? Current version us 9.2.0 but latest Fabric JS is using 5.0.1
Thanks
Peter

**Comment by ChrispyBites** [comment]
Because, based on the number of open issues and the lack of response from the team ostensibly in charge of this, Microsoft is not supporting this library anymore.

**Comment by cmk128** [comment]
It is crazy if microsoft don't support this library and don't announce it, but thanks
