### ISSUE TITLE
Error on getting v1.5.0 from sharepointonline.com

### ISSUE THREAD

**Issue by mvpkenlin** [OfficeDev/office-ui-fabric-js#358]
I added reference to 
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.5.0/css/fabric.components.min.css" />

but getting error. 

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.5.0/css/fabric.components.min.css

**Comment by mikewheaton** [comment]
Thanks for reporting this, @mvpkenlin, we forgot to publish the latest release to the CDN. We're adding it now and will post an update back here when it's available.

**Comment by mikewheaton** [comment]
Version 1.5.0 is now available on the CDN: https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.5.0/css/fabric.components.min.css
