### ISSUE TITLE
How to capture event object on onChanged event

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-js#361]
I am creating a row with few cells. I am giving option to user to enter more rows if they want. When value get changed, I want to store those values in `state` object. I am using [Office UI Fabric TextField](https://developer.microsoft.com/en-us/fabric#/components/textfield) control. This is having onChanged event, but this is capturing only the value of the textbox. But I want to capture the event or simply, I want to get the `data-id` attribute of it's parent element which is a row. I am implementing this in SharePoint Spfx with React framework. 
![addexpnserow](https://user-images.githubusercontent.com/7568187/35514001-db8e048c-052a-11e8-9279-21cfae88ace4.PNG)

**Comment by mikewheaton** [comment]
Sorry for the confusion here, but the project you're looking for is [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react). If you open an issue over there someone should be able to help.

**Comment by ymihir** [comment]
Ok Thanks.
