### ISSUE TITLE
One Mono-repo contains all office-ui-fabric-* packages

### ISSUE THREAD

**Issue by abdullahsalem** [OfficeDev/office-ui-fabric-js#368]
@mikewheaton I think that it would be more efficient if all office fabric family repos are moved into one single repo ([Mono-repo](https://medium.com/@patrickleet/mono-repo-or-multi-repo-why-choose-one-when-you-can-have-both-e9c77bd0c668)), and managed by [Lerna](https://github.com/lerna/lerna).

**Comment by Jahnp** [comment]
Hi @abdullahsalem , thanks for the suggestion. This is something that's on our radar, but don't have immediate plans for. We'd also likely manage it with [Rush](https://github.com/Microsoft/web-build-tools/wiki/Rush), which is what we use to manage packages within Fabric React. I'm going to go ahead and close this until we have a more concrete plan for this area.

**Comment by abdullahsalem** [comment]
Thanks @Jahnp for the reply and letting me know this awesome project (**Rush**)
