### ISSUE TITLE
when i am implementing office ui fabric react people picker the suggestions are coming on the top left corner?css isue

### ISSUE THREAD

**Issue by tyagia10** [OfficeDev/office-ui-fabric-js#372]
![image](https://user-images.githubusercontent.com/12757782/40847204-0552153c-65bc-11e8-8888-2e0e804b537b.png)

**Comment by mikewheaton** [comment]
Since you mentioned React, I believe you're looking for the [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) project. Please open an issue there.
