### ISSUE TITLE
Are there any examples in Javascript and not React?

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-js#381]
I want to use this for forms in SharePoint but all the examples i'm finding are in React and I can't find documentation on in vanilla JS?

**Comment by seriewe** [comment]
Here are all Components and a sample for each component with HTML Markup and plain JS:

https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/COMPONENTSLIST.md
