### ISSUE TITLE
Can anyone show me how to make ui fabric ms-drop down multiple

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#39]
_From @johnnyongesa on June 14, 2016 9:23_

Adding the `class="multiple"` keyword does not change anything

_Copied from original issue: OfficeDev/office-ui-fabric-core#663_

**Comment by mikewheaton** [comment]
Could you send a link or screenshot of the functionality you're looking for? I wonder if something like [jQuery UIs autocomplete with multiple values](http://jqueryui.com/autocomplete/#multiple) is what you're looking for. We have this on [our roadmap](https://github.com/OfficeDev/office-ui-fabric/blob/master/ghdocs/ROADMAP.md) but the work is not scheduled.

**Comment by ericthompson** [comment]
Closing without extra info - please feel free to reopen with more details.
