### ISSUE TITLE
Pivot: clicking below the label does not cause any action

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#42]
_From @marekszala-microsoft on June 6, 2016 7:13_

When I click the space between a label and its bottom bar a selection animation is played but the selected item does not change.
See the attachment:
![pivotclickbug](https://cloud.githubusercontent.com/assets/19771931/15814406/ef56e9fa-2bc6-11e6-9ed8-ad8d9107ec9e.gif)

_Copied from original issue: OfficeDev/office-ui-fabric-core#647_

**Comment by mikewheaton** [comment]
Thank you for reporting this bug, @marekszala-microsoft

**Comment by ericthompson** [comment]
No longer repros as of v1.1.0:
![pivots](https://cloud.githubusercontent.com/assets/1420854/19623468/bf416af4-987e-11e6-89b3-d062205707bf.gif)
