### ISSUE TITLE
ListItem: Checkbox icon misaligned

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#49]
_From @mikewheaton on June 5, 2016 21:50_

On iOS the checkmark sits too high in its box.

![image](https://cloud.githubusercontent.com/assets/1382445/15808467/b98b34d8-2b2c-11e6-8e0b-eccc4f68080a.png)

_Copied from original issue: OfficeDev/office-ui-fabric-core#640_

**Comment by leddie24** [comment]
Closing issue, seemed to be resolved now (iphone 6s, safari on browserstack)
![screen shot 2016-09-08 at 11 43 19 am](https://cloud.githubusercontent.com/assets/1291968/18362141/7b73ac02-75b9-11e6-8344-c5d0cf792bde.png)
