### ISSUE TITLE
[Breadcrumb]: Weird character in SCSS

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#7]
_From @atneik on July 28, 2016 21:39_

At end of line 136: `@media screen and (max-width: $ms-screen-md-max) {å`

_Copied from original issue: OfficeDev/office-ui-fabric-core#752_

**Comment by ericthompson** [comment]
Really complicated - let's see if we can figure it out.

**Comment by atneik** [comment]
I think it should be just a matter of removing `å`character.
