### ISSUE TITLE
New control request - Timepicker

### ISSUE THREAD

**Issue by sivarajanr** [OfficeDev/office-ui-fabric-js#79]
I am looking a timepicker control in Office UI Fabric, similar to this https://github.com/jonthornton/jquery-timepicker

**Comment by ericthompson** [comment]
Thanks, @sivarajanr - good suggestion. I've added this to [the roadmap](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/ROADMAP.md). Closing for now.
