### ISSUE TITLE
What is the purpose of checkbox input in Toggle

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-ui-fabric-js#84]
Toggle component sample includes the following element:
`<input type="checkbox" class="ms-Toggle-input" />`
What is the purpose of this element, since the component works fine without it?

**Comment by manndave** [comment]
I don't have my VM running to check, but I believe it is the form control that stores your selected value.  The Toggle element is essentially just a visual enhancement sitting on top of a standard checkbox input.

**Comment by mikewheaton** [comment]
Yes, this hidden element is there so that the Toggle can be used as an input in a regular HTML form, with its value included when the form is submitted. JavaScript is used to check/uncheck this hidden element.
