### ISSUE TITLE
Question: Fix inconsistencies in Handlebars markup/JSON?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-js#89]
I'm working my way through the Snippet-generator gulp task and am noticing some inconsistencies in the Handlebars markup/JSON.  For example:
- sometimes a label property in the JSON is called "title" and sometimes "label"
- sometimes a check is made to see if a property exists in the JSON before being used and sometimes the check is not made, the property is just used
- some properties in the Handlebars markup do not exist in the JSON

This is making the parsing of the markup to generate the snippets difficult.  Is there any reason not to make a pass through the .hbs and .json files and standardize everything?  That would make snippet generation much easier.  I've already started down this road, so if the team is OK with it, I'll finish and do a PR.

Let me know.

Thanks,

Dave

**Comment by mikewheaton** [comment]
That would be very much appreciated! Several of us were sprinting to get these templates together and, as you've seen, weren't always consistent in how we wrote them. Looking forward to your PR. 😄

**Comment by Jahnp** [comment]
That would be amazing! Thanks a ton @manndave!

**Comment by ericthompson** [comment]
Yes, thanks @manndave!
