### ISSUE TITLE
RadioButton Component  does not work in IE

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-ui-fabric-js#90]
This can be reproduced by opening the sample index.html in documentation

The problem is that IE Custom Events work differently.

The solution is here: http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work

**Comment by ericthompson** [comment]
Looking into this soon - feel free to submit a PR if you have a fix in the meantime :smile:
