### ISSUE TITLE
Persona uses a non-semantic display:table and display:table-cell for arrangement 

### ISSUE THREAD

**Issue by brian-g** [OfficeDev/office-ui-fabric-js#94]
The Persona uses a non-semantic usage of display:table and display:table-cell for arrangement. The reason why this is non-semantic is that the data displayed in the Persona component is not tabular data. As such, screen readers will try to interpret the results as table.

**Comment by mikewheaton** [comment]
Have you confirmed the problem when testing with a screen reader? My understanding is that screen readers don't treat `display:table` as tabular data – it's recognized as being strictly a layout method and doesn't override the HTML structure.

From [Why display: table shouldn’t be frowned upon](https://www.thecssninja.com/css/why-display-table-shouldnt-be-frowned-upon):

> ...CSS is purely presentational and setting something as display: table is not the same as using the table tag. A screen reader going over a layout styled using the CSS table model will not get confused...

This article is a few years old and I couldn't track down much information on the topic, so it's possible that screen readers have changed. We'd just want to confirm the issue before making any updates here.

**Comment by brian-g** [comment]
It does appear that there is some [variance in screen readers] (http://www.456bereastreet.com/archive/201110/using_displaytable_has_semantic_effects_in_some_screen_readers/), and probably not enough that it matters.
